name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable && rustup default stable && rustup component add rustfmt clippy
          # Add problem matcher for Rust: https://github.com/actions/toolkit/blob/main/docs/commands.md#problem-matchers
      - run: echo "::add-matcher::.github/rust_problem_matcher.json"
      - name: Run lint
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy
      - run: echo "::remove-matcher owner=rust::"
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable && rustup default stable && rustup component add rustfmt clippy
      - run: echo "::add-matcher::.github/rust_problem_matcher.json"
      - name: Test
        run: cargo test --all
      - run: echo "::remove-matcher owner=rust::"
  # docs_deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.3.1
  #     - name: Build the book
  #       run: cd guide && mdbook build
  #     - name: Deploy
  #       if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #       uses: JamesIves/github-pages-deploy-action@4.1.4
  #       with:
  #         branch: master
  #         folder: guide/book
  #         token: ${{ secrets.GITHUB_TOKEN }}
